namespace: "idec"
hostname: idec-grape.home.lab
fullnameOverride: "idec-grape"

security:
  useGeneratedCert: false
  certmanager:
    generateCert: true
    issuer:
      name: "kearos-issuer"
      kind: "ClusterIssuer"

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false

podLabels:
  app: "idec-grape"

podAnnotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "false"

image:
  pullPolicy: IfNotPresent
  tag: 0.1.27

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    memory: 256Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

httpproxy:
  enabled: false

istio:
  enabled: true

# map to arm64 nodes
nodeSelector:
    kubernetes.io/arch: arm64
