cluster:
  name: "local"
  url: "127.0.0.1:443"

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
        add-additional-paths=true:
          enabled: true
          additional-paths: "/liveness, /readiness"