apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gitstafette-image-builds
  namespace: gsf
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stdout.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
    - name: base
      description: version Base to query Git tags for (e.g., v2.1.*)
      type: string
    - name: gitrevision
      description: git revision to checkout
    - name: image
      description: image to use for the git-next-tag task
      type: string
      default: ghcr.io/joostvdg/git-next-tag:0.5.4-alpine
    - name: dockerfile
      description: dockerfile to use for the kaniko task
      type: string
      default: Dockerfile
    - name: registry
      description: registry to push to
      type: string
      default: ghcr.io
    - name: repo
      description: repo to push to
      type: string
      default: joostvdg/gitstafette/server
    - name: tag
      description: tag to push to
      type: string
      default: latest
  workspaces:
    - name: checkout
      description: |
        This workspace contains the cloned repo files, so they can be read by the
        next task.
    - name: registry-credentials
      description: |
        This workspace contains the registry credentials, so they can be read by the
        next task.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: checkout
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.gitrevision)
    - name: git-next-tag
      runAfter: ["fetch-source"]
      taskRef:
        name: git-next-tag
      workspaces:
        - name: source
          workspace: checkout
      params:
        - name: base
          value: $(params.base)
        - name: image
          value: $(params.image)
    - name: create-and-push-git-tag
      runAfter: ["git-next-tag"]
      taskRef:
        name: github-create-tag
      workspaces:
        - name: source
          workspace: checkout
      params:
        - name: TAG
          value: $(tasks.git-next-tag.results.NEXT_TAG)
        - name: GITHUB_USERNAME
          value: tekton-bot
        - name: GITHUB_EMAIL
          value: joostvdg+tekton-bot@gmail.com
    - name: server-image-build-and-push-arm64
      runAfter: ["git-next-tag"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: checkout
        - name: dockerconfig
          workspace: registry-credentials
      params:
        - name: IMAGE
          value: "$(params.registry)/$(params.repo):$(tasks.git-next-tag.results.NEXT_TAG)"
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: EXTRA_ARGS
          value: [--customPlatform=linux/arm64, --skip-tls-verify-registry=harbor.home.lab]
    - name: server-image-build-and-push-amd64
      runAfter: ["git-next-tag"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: checkout
        - name: dockerconfig
          workspace: registry-credentials
      params:
        - name: IMAGE
          value: "$(params.registry)/$(params.repo):$(tasks.git-next-tag.results.NEXT_TAG)"
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: EXTRA_ARGS
          value: [--customPlatform=linux/amd64, --skip-tls-verify-registry=harbor.home.lab]
