{{ if .Values.security.certmanager.generateCert }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "tls.certName" . }}
  namespace: istio-system
spec:
  secretName: {{ include "tls.secretName" . }}
  issuerRef:
    name: {{ .Values.security.certmanager.issuer.name }}
    kind: {{ .Values.security.certmanager.issuer.kind }}
  commonName: {{ .Values.hostname }}
  dnsNames:
    - {{ .Values.hostname }}
{{ end }}