{{ if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "server.fullname" . }}
spec:
  hosts:
    - {{ .Values.hostname }}
  gateways:
    - {{ include "server.fullname" . }}

  http:
    route:
      - destination:
        host: {{ include "server.fullname" . }}
        port:
          number: 80
{{- end }}